file:
  base:
    path: "E:"        #基本目录父目录
    folder: images    #基本目录
    regex: ".+(.JPEG|.jpeg|.JPG|.jpg)"
    log:
      folder: D:\logs
spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  datasource:
    url: jdbc:mysql://zhuyc.top:13306/file?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    show-sql: true
    open-in-view: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true
server:
  port: 9999
  servlet:
    context-path: /fs
